drop table if exists personas CASCADE 
drop table if exists planetas CASCADE 

create table personas (id integer generated by default as identity, cantidad_visitas integer, estatura_en_metros float, fecha_nacimiento date not null, genero varchar(1) not null, nombre varchar(255) not null, numero_identificacion integer not null, peso_en_kilogramos float, planeta_id integer, primary key (id))
create table planetas (id integer generated by default as identity, cantidad_visitas integer, clima varchar(255), diametro integer not null, nombre varchar(255) not null, periodo_rotacion float not null, terreno varchar(255) not null, primary key (id))

alter table personas add constraint UK_personas unique (numero_identificacion)
alter table planetas add constraint UK_planetas unique (nombre)
alter table personas add constraint FK_personas foreign key (planeta_id) references planetas

INSERT INTO planetas (id, nombre, periodo_rotacion, diametro, terreno, clima) VALUES (900, 'Mercurio', 58.6667, 4878, 'Rocoso', 'Variado')
INSERT INTO planetas (id, nombre, periodo_rotacion, diametro, terreno, cantidad_visitas) VALUES (901, 'Venus', 243, 12100, 'Arenoso', 1)
INSERT INTO planetas (id, nombre, periodo_rotacion, diametro, terreno, clima, cantidad_visitas) VALUES (902, 'Tierra', 1, 12756, 'Rocoso', 'Templado', 150)
INSERT INTO planetas (id, nombre, periodo_rotacion, diametro, terreno, cantidad_visitas) VALUES (903, 'Marte', 1.03, 6787, 'Arenoso', 101)
INSERT INTO planetas (id, nombre, periodo_rotacion, diametro, terreno, clima, cantidad_visitas) VALUES (904, 'Saturno', 0.426, 120536, 'Rocoso', 'Variado', 21)

INSERT INTO personas (id, numero_identificacion, nombre, fecha_nacimiento, genero, estatura_en_metros, peso_en_kilogramos, cantidad_visitas, planeta_id) VALUES (900, 123456, 'Jhon Fredy', '1989-05-15', 'M', 1.66, 91.7, 56, 902)
INSERT INTO personas (id, numero_identificacion, nombre, fecha_nacimiento, genero, estatura_en_metros, cantidad_visitas, planeta_id) VALUES (901, 654321, 'Paola', '1989-11-10', 'F', 1.63, 200, 902)
INSERT INTO personas (id, numero_identificacion, nombre, fecha_nacimiento, genero, cantidad_visitas, planeta_id) VALUES (902, 456789, 'Salomé', '2014-06-27', 'F', 230, 902)
INSERT INTO personas (id, numero_identificacion, nombre, fecha_nacimiento, genero, estatura_en_metros, peso_en_kilogramos, planeta_id) VALUES (903, 15963, 'Alexander', '1991-08-31', 'M', 1.71, 95, 901)
INSERT INTO personas (id, numero_identificacion, nombre, fecha_nacimiento, genero, cantidad_visitas, planeta_id) VALUES (904, 35741, 'Socorro', '1970-12-08', 'F', 13, 903)
INSERT INTO personas (id, numero_identificacion, nombre, fecha_nacimiento, genero, cantidad_visitas, planeta_id) VALUES (905, 258, 'Fredi', '1967-12-09', 'M', 2, 903)
INSERT INTO personas (id, numero_identificacion, nombre, fecha_nacimiento, genero, estatura_en_metros, cantidad_visitas, planeta_id) VALUES (906, 17, 'Luz', '1962-01-10', 'F', 1.53, 81, 904)